[tool]
[tool.commitizen]
bump_message = "release $current_version â†’ $new_version [skip-ci]"
name = "cz_conventional_commits"
tag_format = "v$version"
version = "0.3.0"
version_files = [ "manifest.json:version" ]
update_changelog_on_bump = true
annotated_tag = true
